image: python:3.7-alpine
stages:
  - test
  - package
  - release

test_3.6:
  stage: test
  image: python:3.6
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  except:
    - schedules

test_3.7:
  stage: test
  image: python:3.7-alpine
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  except:
    - schedules
