image: python:3.7-alpine

variables:
  PACKAGE_NAME: encoding_tools

stages:
  - test
  - build
  - release

python-3.6:
  stage: test
  image: python:3.6-alpine
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  except:
    - schedules

python-3.7:
  stage: test
  image: python:3.7-alpine
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  except:
    - schedules

build-package:
  stage: build
  image: python:3.7-alpine
  variables:
    TWINE_REPOSITORY_URL: $TEST_PYPI_REPO_URL
    TWINE_REPOSITORY: $TEST_PYPI_REPO_URL
    TWINE_USERNAME: $TEST_PYPI_USERNAME
    TWINE_PASSWORD: $TEST_PYPI_PASSWORD
  before_script:
    - pip install -r requirements.txt
    - pip install twine
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

    - pip install $PACKAGE_NAME --index-url https://test.pypi.org/simple/
  only:
    - tags
  except:
  - schedules

mirror-to-github:
  stage: release
  image: debian:stretch-slim
  variables:
    GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
  before_script:
    - apt-get update -y && apt-get install openssh-client git -y
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_SSH_KEY")
    - git remote add github $GITHUB_REPO_LINK || true
  script:
    - git push -f github master
    - git push -f github master --tags
  except:
  - schedules

upload-to-pypi:
  stage: release
  image: python:3.7-alpine
  variables:
    TWINE_REPOSITORY_URL: $PYPI_REPO_URL
    TWINE_REPOSITORY: $PYPI_REPO_URL
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  before_script:
    - pip install -r requirements.txt
    - pip install twine
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - tags
  except:
  - schedules
